---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_solo
  require_chef_omnibus: 12
  data_path: test/shared

platforms:
  - name: centos-7.1
  - name: ubuntu-14.04
  - name: debian-8.0
  - name: fedora-21
  - name: windows-2012r2
    driver:
      box: dhoer/windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[java_se::default]
    excludes:
      - windows-2012r2
  - name: alt_home
    run_list:
      - recipe[java_se::default]
    includes:
      - windows-2012r2
    attributes:
      java_se:
        java_home:
          C:\my\java\jdk
